source/tutorials/version-bumping.txt
Staged: https://docs-mongodbcom-staging.corp.mongodb.com/meta/robertjustice/version-bumpiing-update/tutorials/version-bumping.html
=> (version-bumping-update) Updates to version bumping.

source/includes/steps-install.yaml, source/includes/steps-repo.yaml, source/tutorials.txt, source/tutorials/install.txt, source/tutorials/repo.txt
https://docs-mongodbcom-staging.corp.mongodb.com/meta/skersch/admonishment/tutorials/repo.html
https://docs-mongodbcom-staging.corp.mongodb.com/meta/skersch/admonishment/tutorials/install.html
Jon D. I removed some steps/simplified in order to address some of your concerns, and added a guide on how to install the tools.
The audience for this will be outside of our team -- not that our team can't use these guides, but we have internal guides for this. We are beginning to get requests from outside the team for folks who want to use our tooling. To make this one step further away from MongoDB-specific content I removed anything that references how we publish, which is information we can continue to share internally.
Thanks!
=> warning about redirects

source/includes/steps-install.yaml, source/snooty.txt, source/tutorials/install.txt
https://docs-mongodbcom-staging.corp.mongodb.com/meta/andrew/update-install-guide/tutorials/install.html
=> Update install guide

source/includes/steps-install.yaml
https://docs-mongodbcom-staging.corp.mongodb.com/meta/andrew/split-first-installation-step/tutorials/install.html
=> Split first installation step into two to prevent writers from skipping it

source/style-guide.txt, source/style-guide/control-panels-and-portals.txt, source/style-guide/user-interface-guidelines.txt
JIRA:
https://jira.mongodb.org/browse/DOCSP-6822
Staging:
https://docs-mongodbcom-staging.corp.mongodb.com/meta/melissamahoney/DOCSP-6822/style-guide.html
=> (DOCSP-6822): Remove cross-org pages until we get buy-in

source/style-guide/blog-guidelines.txt
JIRA:
https://jira.mongodb.org/browse/DOCSP-6823
Staging:
https://docs-mongodbcom-staging.corp.mongodb.com/meta/melissamahoney/DOCSP-6823/style-guide/blog-guidelines.html
=> (DOCSP-6823): Update & republish Blogs Guidelines page

conf.py, source/style-guide.txt
@melissamahoney-mongodb : Add link to [LeafyGreen](https://docs-mongodbcom-staging.corp.mongodb.com/meta/docsworker-xlarge/DOCSP-7298/style-guide.html). I think the copy works, but please edit.
=> (DOCSP-7298): Add LeafyGreen UI link.

source/includes/steps-install.yaml
JIRA: https://jira.mongodb.org/browse/DOCSP-8823
Staging: https://docs-mongodbcom-staging.corp.mongodb.com/meta/jdestefano/DOCSP-8823/tutorials/install.html#install-mut
=> DOCSP-8823 - Add troubleshooting step if mut install fails.

conf.py, source/includes/steps-guides.yaml, source/includes/styles/corrections.rst
@melissamahoney-mongodb : [Staged the change to Guides that caused the error](https://docs-mongodbcom-staging.corp.mongodb.com/meta/docsworker-xlarge/DOCSP-11309/tutorials/guide.html#document-the-content-with-steps-required-to-complete-the-tutorial).
---
[Builds without errors on `style-guide-v3`.](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=5f1b44682f9a5cfb5bc284ea)
=> (DOCSP-11309) Fix general errors

source/style-guide/terminology/general-term-guidelines/use-consistent-time-references.txt
[Staged](https://docs-mongodbcom-staging.corp.mongodb.com/meta/docsworker-xlarge/DOCSP-11383/style-guide/terminology/general-term-guidelines/use-consistent-time-references.html)
---
[Builds without errors on `style-guide-v3`.](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=5f1d033f2f9a5cfb5b080d78)
=> (DOCSP-11383) Update time and space page

source/style-guide/style/product-names-version-numbers.txt
[Staged](https://docs-mongodbcom-staging.corp.mongodb.com/meta/docsworker-xlarge/DOCSP-11377/style-guide/style/product-names-version-numbers.html)
---
[Builds without errors on `style-guide-v3`.](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=5f1e602f2f9a5cfb5b3a5cd4)
=> (DOCSP-11377) Update Product Names and Versions page

source/style-guide/terminology/general-term-guidelines/use-short-words.txt
@ccho-mongodb : [Staged](https://docs-mongodbcom-staging.corp.mongodb.com/meta/docsworker-xlarge/DOCSP-11382/style-guide/terminology/general-term-guidelines/use-short-words.html)
---
[Builds without errors on `style-guide-v3`.](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=5f1f9c912f9a5cfb5b6b1d71)
=> (DOCSP-11382) Update short words page

source/style-guide/style/cloud-account-info.txt
@ccho-mongodb : [Staged](https://docs-mongodbcom-staging.corp.mongodb.com/meta/docsworker-xlarge/DOCSP-11404/style-guide/style/cloud-account-info.html)
---
[Builds without errors on `style-guide-v3`.](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=5f1f9d2e2f9a5cfb5b6b3354)
=> (DOCSP-11404) API placeholders

source/style-guide/style/lists.txt
[Staged](https://docs-mongodbcom-staging.corp.mongodb.com/meta/docsworker-xlarge/DOCSP-11376/style-guide/style/lists.html)
---
[Builds without errors on `master`.](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=5f1d06042f9a5cfb5b0874f4)
=> (DOCSP-11376) Update lists page

conf.py, config/intersphinx.yaml, source/style-guide/style/links-and-cross-references.txt
[Staged](https://docs-mongodbcom-staging.corp.mongodb.com/meta/docsworker-xlarge/DOCSP-11375/style-guide/style/links-and-cross-references.html)
---
[Builds without errors on `style-guide-v3`.](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=5f1e5a312f9a5cfb5b3982df)
=> (DOCSP-11375) Update Links page

source/style-guide/style/titles-and-headings.txt
@andf-mongodb : [Staged](https://docs-mongodbcom-staging.corp.mongodb.com/meta/docsworker-xlarge/DOCSP-11379/style-guide/style/titles-and-headings.html)
---
[Builds without errors on `style-guide-v3`.](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=5f209a432f9a5cfb5b9c0ea3)
=> (DOCSP-11379) Update Titles and Heading page

source/style-guide/style/urls.txt
@andf-mongodb : [Staged](https://docs-mongodbcom-staging.corp.mongodb.com/meta/docsworker-xlarge/DOCSP-11381/style-guide/style/urls.html)
---
[Builds without errors on `style-guide-v3`.](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=5f20623a2f9a5cfb5b93b322)
=> (DOCSP-11381) Update URLs page

source/style-guide/style/ip-addresses.txt
@andf-mongodb : [Staged](https://docs-mongodbcom-staging.corp.mongodb.com/meta/docsworker-xlarge/DOCSP-11374/style-guide/style/ip-addresses.html)
---
[Builds without errors on `style-guide-v3`.](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=5f209aea2f9a5cfb5b9c277f)
=> (DOCSP-11374) Update IP Address page

source/style-guide/style/capitalization.txt
@andf-mongodb : [Staged](https://docs-mongodbcom-staging.corp.mongodb.com/meta/docsworker-xlarge/DOCSP-11372/style-guide/style/capitalization.html)
---
[Builds without errors on `style-guide-v3`.](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=5f209bc22f9a5cfb5b9c485d)
=> (DOCSP-11372) Update Caps page

source/style-guide/writing/use-present-tense.txt
@andf-mongodb : [Staged](https://docs-mongodbcom-staging.corp.mongodb.com/meta/docsworker-xlarge/DOCSP-11368/style-guide/writing/use-present-tense.html)
---
[Builds without errors on `style-guide-v3`.](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=5f209d702f9a5cfb5b9c8874)
=> (DOCSP-11368) Update Present Tense page

source/style-guide/writing/use-active-voice.txt
@andf-mongodb : [Staged](https://docs-mongodbcom-staging.corp.mongodb.com/meta/docsworker-xlarge/DOCSP-11367/style-guide/writing/use-active-voice.html)
---
[Builds with expected errors on `master`.](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=5f209eb52f9a5cfb5b9cbdaf)
=> (DOCSP-11367) Update Use Active Voice page

source/style-guide/writing/use-effective-verbs.txt, source/style-guide/writing/write-to-the-user.txt
@andf-mongodb : [Staged](https://docs-mongodbcom-staging.corp.mongodb.com/meta/docsworker-xlarge/DOCSP-11369/style-guide/writing/write-to-the-user.html)
---
[Builds without errors on `style-guide-v3`.](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=5f20a2b52f9a5cfb5b9d53df)
=> (DOCSP-11369) Update Person and Mood page

source/style-guide/style/prepositions.txt
[JIRA](https://jira.mongodb.org/browse/DOCSP-11393)
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/meta/docsworker-xlarge/DOCSP-11393/style-guide/style/prepositions.html)
=> (DOCSP-11393): update Prepositions

source/style-guide/style/names.txt
[JIRA](https://jira.mongodb.org/browse/DOCSP-11391)
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/meta/docsworker-xlarge/DOCSP-11391/style-guide/style/names.html)
My initial issue with this topic was because I misread "John Smith" as "John Doe". But used the opportunity to take diversity/globalization into account.
=> (DOCSP-11391): Update Names to include diversity

source/style-guide/style/tasks.txt
[JIRA](https://jira.mongodb.org/browse/DOCSP-11397)
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/meta/docsworker-xlarge/DOCSP-11397/style-guide/style/tasks.html)
Added a Considerations section.
=> (DOCSP-11397): Add 'Considerations' to Tasks page

source/style-guide/writing/write-for-accessibility.txt
[JIRA](https://jira.mongodb.org/browse/DOCSP-11403)
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/meta/docsworker-xlarge/DOCSP-11403/style-guide/writing/write-for-accessibility.html)
Initially opened this ticket thinking I needed to update the guidance around tables, but I actually think its fine. So these are just typo/formatting fixes.
=> (DOCSP-11403): Update Write for Accessibility

source/style-guide/style/abbreviations.txt
@andf-mongodb : [Staged](https://docs-mongodbcom-staging.corp.mongodb.com/meta/docsworker-xlarge/DOCSP-11371/style-guide/style/abbreviations.html)
---
[Builds without errors on `style-guide-v3`](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=5f20a3902f9a5cfb5b9d7409)
=> (DOCSP-11371) Update abbreviations page

source/style-guide/writing/write-clear-concise-sentences-paragraphs.txt
@andf-mongodb : [Staged](https://docs-mongodbcom-staging.corp.mongodb.com/meta/docsworker-xlarge/DOCSP-11370/style-guide/writing/write-clear-concise-sentences-paragraphs.html)
---
[Builds without errors on `style-guide-v3`.](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=5f1efcef2f9a5cfb5b51cba6)
=> (DOCSP-11370) Update concise content page

source/style-guide/style/email-addresses.txt
[JIRA](https://jira.mongodb.org/browse/DOCSP-11406)
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/meta/docsworker-xlarge/DOCSP-11406/style-guide/style/email-addresses.html)
=> (DOCSP-11406): Update Email Addresses page

source/style-guide/writing/use-effective-verbs.txt
[JIRA](https://jira.mongodb.org/browse/DOCSP-11402)
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/meta/docsworker-xlarge/DOCSP-11402/style-guide/writing/use-effective-verbs.html#don-t-humanize-inanimate-objects)
=> (DOCSP-11402): Remove repetition in Don't Humanize Inanimate Objects

source/style-guide/style/telephone-numbers.txt
[JIRA](https://jira.mongodb.org/browse/DOCSP-11398)
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/meta/docsworker-xlarge/DOCSP-11398/style-guide/style/telephone-numbers.html)
=> (DOCSP-11398): Update Telephone Numbers page

source/style-guide/style/punctuation.txt
[JIRA](https://jira.mongodb.org/browse/DOCSP-11394)
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/meta/docsworker-xlarge/DOCSP-11394/style-guide/style/punctuation.html)
=> (DOCSP-11394): Update Punctuation page

source/style-guide/style/voice-and-tone.txt
[JIRA](https://jira.mongodb.org/browse/DOCSP-11399)
[Staging](https://docs-mongodbcom-staging.corp.mongodb.com/meta/docsworker-xlarge/DOCSP-11399/style-guide/style/voice-and-tone.html)
=> (DOCSP-11399): Update Voice & Tone w/ JD feedback

source/style-guide/error-message-guidelines.txt, source/style-guide/style/contractions.txt, source/style-guide/style/dates.txt, source/style-guide/style/file-types.txt, source/style-guide/style/glossaries.txt, source/style-guide/style/index.txt, source/style-guide/style/keyboard-keys.txt, source/style-guide/style/messages.txt, source/style-guide/style/numbers.txt, source/style-guide/style/plurals.txt, source/style-guide/style/time.txt, source/style-guide/terminology/concise-terms.txt, source/style-guide/terminology/general-term-guidelines/use-consistent-terms.txt, source/style-guide/terminology/index.txt
[Builds without errors on `style-guide-v3`.](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=5f25e5bd2f9a5cfb5b5cdba1)
=> (DOCSP-11541) Remove pending approval banner

source/style-guide/style/placeholder-variable-text.txt
@ccho-mongodb : [Staged](https://docs-mongodbcom-staging.corp.mongodb.com/meta/docsworker-xlarge/DOCSP-11408/style-guide/style/placeholder-variable-text.html). This is partially aspirational, so some guidance may not be deployed in full, yet.
---
[Builds without errors on `style-guide-v3`.](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=5f283ccf2f9a5cfb5ba0eb34)
=> (DOCSP-11408) Update placeholder page

conf.py, source/includes/steps-guides.yaml, source/includes/styles/corrections.rst
Resolves a conflict for the larger Style Guide 3.0 changes.
---
[Builds without errors on `master`.](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=5f29187c2f9a5cfb5bc5309e)
=> Style Guide prep fixes

source/style-guide/error-message-guidelines.txt, source/style-guide/quickstart.txt, source/style-guide/revision-history.txt, source/style-guide/style/cloud-account-info.txt
[Builds without errors on `master`.](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=5f291f892f9a5cfb5bc64daf)
=> Fixed a few DIFF messages in the Style Guide

source/style-guide.txt
@jdestefano-mongo : [Staged](https://docs-mongodbcom-staging.corp.mongodb.com/meta/docsworker-xlarge/DOCSP-11630/style-guide.html)
---
[Builds without errors on `master`.](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=5f2ac4812f9a5cfb5b16bfde)
=> (DOCSP-11630) Updated title to Docs Style Guide

source/style-guide/includes/terms/l.rst, source/style-guide/style/capitalization.txt, source/style-guide/style/product-names-version-numbers.txt, source/style-guide/terminology/terms-for-global-audience.txt, source/style-guide/writing/use-that-which-correctly.txt, source/style-guide/writing/write-clear-concise-sentences-paragraphs.txt
@JuliaMongo , @melissamahoney-mongodb : Please review to see if these changes align with what was noted in [DOCSP-12745](https://jira.mongodb.org/browse/DOCSP-12745). Thanks!
These include:
- [Item 1](https://docs-mongodbcom-staging.corp.mongodb.com/meta/docsworker-xlarge/DOCSP-12745/style-guide/terminology/terms-for-global-audience/)
- [Item 2](https://docs-mongodbcom-staging.corp.mongodb.com/meta/docsworker-xlarge/DOCSP-12745/style-guide/style/capitalization/)
- [Item 3](https://docs-mongodbcom-staging.corp.mongodb.com/meta/docsworker-xlarge/DOCSP-12745/style-guide/writing/write-clear-concise-sentences-paragraphs/#avoid-expletive-structures)
- [Item 4](https://docs-mongodbcom-staging.corp.mongodb.com/meta/docsworker-xlarge/DOCSP-12745/style-guide/style/product-names-version-numbers.html) …
=> (DOCSP-12745) Fixing errors

source/redirects.txt
Staging: 
https://docs-mongodbcom-staging.corp.mongodb.com/meta/docsworker-xlarge/update-redirects/redirects.html
=> Must include trailing slashes and update for Snooty.

source/style-guide/style/numbers.txt
[STAGING](https://mongodbcom-cdn.website.staging.corp.mongodb.com/docs-qa/docs-meta/docsworker-xlarge/DOCSP-22901-units-format/style-guide/style/numbers.html)
[JIRA](https://jira.mongodb.org/browse/DOCSP-22901)
=> DOCSP-22901 units format

worker.sh
=> updated worker.sh

source/includes/procedure-example-compact.rst, source/includes/procedure-example-connected.rst, source/includes/procedure-example-default.rst, source/includes/procedure-example-normal.rst, source/includes/tables-example-alignment.rst, source/includes/tables-example-no-widths.rst, source/includes/tables-example-stub-columns.rst, source/includes/tables-example-width.rst, source/includes/tables-example.rst, source/includes/tabs-example-custom.rst, source/includes/tabs-example-preconfigured.rst, source/reference/procedures.txt, source/reference/tables.txt, source/reference/tabs.txt
[Procedures](https://docs-mongodbcom-staging.corp.mongodb.com/meta/docsworker-xlarge/feature-skunkworks/reference/procedures/)
[Tabs](https://docs-mongodbcom-staging.corp.mongodb.com/meta/docsworker-xlarge/feature-skunkworks/reference/tabs/)
[Tables](https://docs-mongodbcom-staging.corp.mongodb.com/meta/docsworker-xlarge/feature-skunkworks/reference/tables/)
=> Procedures, Tabs, Tables

worker.sh
Enable next gen builds.
Based off a PR from @davemungo
=> add worker.sh

snooty.toml
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=637d1bb7ed8015c14bcea810)
=> (DOCSP-26669): Expanded the intersphinx array.

snooty.toml, source/practices.txt, source/snooty.txt
[JIRA](https://jira.mongodb.org/browse/DOCSP-27404)
[STAGING](https://docs-mongodbcom-staging.corp.mongodb.com/meta/docsworker-xlarge/pierwill-patch-2-snooty/style-guide/)
Also add a TOC entry.
=> (DOCSP-27404): Update VS Code snooty installation instructions

source/redirects.txt, source/reference/eval.txt, source/reference/template.txt, source/reference/test-code.txt, source/reference/xmlrole.txt, source/style-guide/includes/terms/b.rst, source/style-guide/includes/terms/c.rst, source/style-guide/includes/terms/d.rst, source/style-guide/includes/terms/e.rst, source/style-guide/includes/terms/g.rst, source/style-guide/includes/terms/h.rst, source/style-guide/includes/terms/i.rst, source/style-guide/includes/terms/l.rst, source/style-guide/includes/terms/n.rst, source/style-guide/includes/terms/o.rst, source/style-guide/includes/terms/p.rst, source/style-guide/includes/terms/q.rst, source/style-guide/includes/terms/r.rst, source/style-guide/includes/terms/s.rst, source/style-guide/includes/terms/t.rst, source/style-guide/includes/terms/u.rst, source/style-guide/includes/terms/v.rst, source/style-guide/includes/terms/w.rst, source/style-guide/style/capitalization.txt, source/style-guide/style/text-formatting.txt, source/style-guide/style/titles-and-headings.txt, source/style-guide/writing/use-that-which-correctly.txt, source/tutorials/version-bumping.txt
[Jira ticket](https://jira.mongodb.org/browse/DOCSP-26883)
=> (DOCSP-26883) Fixes rST formatting error that broke See Also notes

source/style-guide/style/capitalization.txt, source/style-guide/style/code-examples.txt, source/style-guide/style/links-and-cross-references.txt, source/style-guide/style/placeholder-variable-text.txt, source/style-guide/style/punctuation.txt, source/style-guide/style/tasks.txt, source/style-guide/style/text-formatting.txt
[STAGING](https://docs-mongodbcom-staging.corp.mongodb.com/meta/docsworker-xlarge/DOCS-14189-issues-in-writing-guidlines/style-guide/)
[JIRA](https://jira.mongodb.org/browse/DOCS-14189)
=> DOCS-14189 issues in writing guidlines

source/style-guide/writing/write-to-the-user.txt
- Jira: https://jira.mongodb.org/browse/DOCSP-27617
- Staging: https://docs-mongodbcom-staging.corp.mongodb.com/meta/docsworker-xlarge/docsp-27617/style-guide/writing/write-to-the-user/
- Build: https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=63d3e4b70ed0ed332ccd6bb0
=> (DOCSP-27617): Typo fix in style guide

.github/pull_request_template.md
You can preview the md using the [rich diff](https://github.com/mongodb/docs-meta/pull/140/files?short_path=b2496e8#diff-b2496e80299b8c3150b1944450bd81c622e04e13d15c411d291db0927d75fd6b).
=> Add a GitHub PR template

source/style-guide/markup/directives/tables.txt
wiki page.
JIRA URL: <https://jira.mongodb.org/browse/DOCSP-30017>
Staging URL: <https://docs-mongodbcom-staging.corp.mongodb.com/meta/docsworker-xlarge/DOCSP-30017/style-guide/markup/directives/tables/>
=> DOCSP-30017 Add link to table style guide

source/style-guide/includes/terms/f.rst, source/style-guide/style/capitalization.txt
wiki page.
[JIRA](https://jira.mongodb.org/browse/DOCSP-30987)
[Staging capitalization](https://docs-mongodbcom-staging.corp.mongodb.com/meta/docsworker-xlarge/DOCSP-30987-capitalize-fCV/style-guide/style/capitalization/#capitalize-most-abbreviations)
[Staging …
=> DOCSP-30985 style guide

source/style-guide/style/punctuation.txt
wiki page.
JIRA URL: None
Staging URL: https://docs-mongodbcom-staging.corp.mongodb.com/meta/docsworker-xlarge/CMOS-capitalization-colon-addition/style-guide/style/punctuation/#colons
=> Added CMOS quote for additional guidance on capitalization after colons

source/style-guide/style/index.txt
wiki page.
Reorder the Version Numbers item to follow alphabetical order.
JIRA URL: None
Staging URL: https://docs-mongodbcom-staging.corp.mongodb.com/meta/docsworker-xlarge/081023-style-items-order/style-guide/style/version/
=> fix alphabetical order of style section

source/redirects.txt
wiki page.
JIRA URL: https://jira.mongodb.org/browse/DOCSP-32590
Staging URL: https://docs-mongodbcom-staging.corp.mongodb.com/meta/docsworker-xlarge/DOCSP-32590/redirects/
=> Remove inaccurate note about Snooty redirects

source/style-guide/includes/terms/i.rst
wiki page.
The include file for terms that start with "i" was missing syntax required to make it a linkable section.
JIRA URL: None
Staging URL: 
https://docs-mongodbcom-staging.corp.mongodb.com/meta/docsworker-xlarge/083123-fix-i-glossary/style-guide/terminology/alphabetical-terms/#i
=> fix alphabetical terms entry for 'i'

source/style-guide/style/abbreviations.txt
wiki page.
JIRA URL: <https://jira.mongodb.org/browse/DOCSP-33817> (related to, but does not solve)
Staging URL: <https://docs-mongodbcom-staging.corp.mongodb.com/meta/docsworker-xlarge/DOCSP-33817/style-guide/style/abbreviations/>
=> Update abbreviations list to match Vale

source/style-guide/markup/directives/metadata.txt
wiki page.
Added meta keyword guidance that directs MongoDB technical writers to internal wiki.
JIRA URL: None
Staging URL: https://preview-mongodbcchomongodb.gatsbyjs.io/meta/113023-add-admonition-meta-keywords/style-guide/markup/directives/metadata/
=> Add mention of taxonomy tagging instructions

source/style-guide/includes/rendered-icon-table.rst
wiki page.
Fixes the non-rendering icon issue.
JIRA URL: [<https://jira.mongodb.org/browse/DOCSP-DOP-4185>](https://jira.mongodb.org/browse/DOP-4185)
Staging URL: https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/c58679996a06128466e9e7f89a1776f36d0cf21a/DOP-4185/meta/caesarbell/master/ …
=> :bug: DOP-4185 updates the icons to render properly

source/style-guide/markup/directives.txt, source/style-guide/markup/directives/sharedinclude.txt
Please read the [Style Guide Review Process](https://wiki.corp.mongodb.com/display/DE/Technical+Writer+Style+Guide+Review+Process) wiki page.
JIRA URL: <https://jira.mongodb.org/browse/DOCSP-34574>
Staging URL: https://preview-mongodbcchomongodb.gatsbyjs.io/meta/DOCSP-34574-sharedinclude-replacement/style-guide/markup/directives/sharedinclude/
=> DOCSP-34574: sharedinclude and replacement descriptions

source/style-guide/style/lists.txt
I updated the note about sentence fragments to capture the sentiments expressed in this [Slack thread](https://mongodb.slack.com/archives/C03NM5RKN2H/p1697553906239079)
[STAGE](https://preview-mongodbcorryroot.gatsbyjs.io/meta/DOCSP-36170/style-guide/style/lists/#introductory-text)
[JIRA](https://jira.mongodb.org/browse/DOCSP-36170)
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65e0a03911db7b04272fa0f4)
wiki page.
- If any reviewer requests changes, address them and …
=> (DOCSP-36170): Updated stem sentence guidance.

source/style-guide/markup/directives/metadata.txt, source/style-guide/seo-guidelines.txt
I tried to better align the SEO guidance with the taxonomy tagging instructions.
[STAGE](https://preview-mongodbcorryroot.gatsbyjs.io/meta/DOCSP-36143/style-guide/seo-guidelines/)
[JIRA](https://jira.mongodb.org/browse/DOCSP-36143)
[BUILD](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65e0ac9611db7b0427346a9c)
wiki page.
they …
=> (DOCSP-36143): Aligned SEO guidance with Taxonomy instructions.

source/style-guide/markup/directives/metadata.txt, source/style-guide/seo-guidelines.txt, source/style-guide/style/links-and-cross-references.txt, source/style-guide/style/urls.txt
I updated the Style Guide in a few places to include IA & SEO information I think is particularly important.
JIRA URL: <https://jira.mongodb.org/browse/DOCSP-33533>
Staging URL: <https://preview-mongodbsarahemlin.gatsbyjs.io/meta/DOCSP-33533/>
Build log: <https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6633fbeeb67dbf804a71e513>
=> IA-related updates to SEO and metadata content

source/style-guide/style/code-examples.txt
wiki page.
Hi @jeff-allen-mongo, @jordan-smith721, @sarahemlin, and @lindseymoore, I made this initial pass on the code example guidance. I updated the guidance for terminal characters because including them makes copy and paste more difficult. I broke up the general guidance from the …
=> (DOCSP-40100): Initial pass on code example guidance.

source/style-guide/includes/terms/d.rst, source/style-guide/includes/terms/t.rst, source/style-guide/style/tasks.txt
wiki page.
I made the following small changes to the Style Guide to address a series of tickets in the backlog.
JIRA URLs:
- https://jira.mongodb.org/browse/DOCSP-11947
- https://jira.mongodb.org/browse/DOCSP-40563
- https://jira.mongodb.org/browse/DOCSP-41106
Staging URLs:
- …
=> (DOCSP-11947), (DOCSP-40563), (DOCSP-41106): Updates for timestamps, procedures, and toggles.

source/style-guide/style/product-names-version-numbers.txt
wiki page.
Added an example for not using MongoDB in a contraction
JIRA URL: <https://jira.mongodb.org/browse/DOCSP-41582>
Staging URL: <https://preview-mongodbshuangela.gatsbyjs.io/meta/DOCSP-41582-style-guide-contraction-ex/style-guide/style/product-names-version-numbers/>
=> DOCSP-41582 add example for using MongoDB as part of a contraction

source/style-guide/seo-guidelines.txt, source/style-guide/style/index.txt, source/style-guide/style/product-names-version-numbers.txt, source/style-guide/style/titles-and-headings.txt, source/style-guide/style/toc-labels.txt, source/style-guide/terminology/general-term-guidelines/use-consistent-terms.txt
I added the following TOC label guidance page and updated other pages with SEO and spelling changes.
wiki page.
JIRA URLs:
- https://jira.mongodb.org/browse/DOCSP-41504
- https://jira.mongodb.org/browse/DOCSP-41866
- https://jira.mongodb.org/browse/DOCSP-41583 …
=> (DOCSP-41504, DOCSP-41866, DOCSP-41583): Adds TOC label guidance, SEO, and spelling updates.

source/style-guide/includes/terms/p.rst, source/style-guide/style/tables.txt
wiki page.
I updated "plug-in" to "plugin".
JIRA URL: https://jira.mongodb.org/browse/DOCSP-42468
Staging URL: https://deploy-preview-177--mongodb-docs-meta.netlify.app/style-guide/terminology/alphabetical-terms/#std-term-plugin
=> (DOCSP-42468): Changed plug-in to plugin.

source/style-guide.txt, source/style-guide/nested-components.txt, source/style-guide/style/callouts.txt, source/style-guide/style/code-examples.txt, source/style-guide/style/tables.txt, source/style-guide/style/tasks.txt
wiki page.
JIRA URL: https://jira.mongodb.org/browse/DOCSP-43893
Staging: https://deploy-preview-179--mongodb-docs-meta.netlify.app/style-guide/nested-components/
=> (DOCSP-43893): Adds nested component guidelines.

source/style-guide/style/toc-labels.txt
wiki page.
Add guidance about using action-oriented TOC labels.
=> Action-oriented TOC labels

source/practices.txt
JIRA URL: <https://jira.mongodb.org/browse/DOCSP-45979>
=> DOCSP-45979 Broken Sphinx link in Style Guide

config/redirects
wiki page.
JIRA URL: <https://jira.mongodb.org/browse/DOP-5553>
Hi all, I'm adding an empty `config/redirects` file to comply with the current Netlify builders' logic to look for a redirects file. There will be no redirects at this time.
=> DOP-5553: Add config/redirects file to avoid builder error
